### ISSUE TITLE
Which ontology of unit of measure shall we use?

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/BONSAI-ontology-RDF-framework#10]
Regarding the ontology of units I went for QUDT because it seems more standard (is W3C member), but I leave the final decision to the domain experts.

There are two options:

1.  Ontology of Units of Measure and Related Concepts
2. QUTD

Here is some relevant material:
 1. the paper on OM [1] and the reviews of the paper [2]
 2. the official websites [3,4]

[1] http://semantic-web-journal.org/sites/default/files/swj177_3.pdf
[2] http://www.semantic-web-journal.net/content/ontology-units-measure-and-related-concepts
[3] http://www.qudt.org/
[4] http://www.ontology-of-units-of-measure.org/

**Comment by kuzeko** [comment]
Final decision should be reflected in: [BEP003](https://github.com/BONSAMURAIS/enhancements/blob/bep3-ontology/beps/0003-bep-ontology.md)

**Comment by cmutel** [comment]
For those of use who aren't familiar with the specs, are there simple examples and/or a comparison of these two systems?

**Comment by kuzeko** [comment]
The best experts comments I know are here:
http://www.semantic-web-journal.net/content/ontology-units-measure-and-related-concepts

I've looked quickly in both formats and it seems that the OM has the "easiest" syntax.

**Comment by agneta20** [comment]
Bo did a review of these ontologies earlier. The OM ontology is much more applicable for our case compared to QUDT. Check here for [Unit](https://github.com/BONSAMURAIS/bonsai/wiki/Data-Storage)
