### ISSUE TITLE
Please provide 1-2 example files in turtle or JSON-LD

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/BONSAI-ontology-RDF-framework#11]

**Comment by kuzeko** [comment]
Examples in [/examples](https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework/tree/master/examples)  should be double-checked and converted also in JSON-LD

**Comment by kuzeko** [comment]
commit https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework/commit/3149f2f5b3c309e219c166037ef77929e38e0e1e
by Elias should address this.

@cmutel please confirm

**Comment by cmutel** [comment]
Thanks everyone!
