### ISSUE TITLE
Define URI for group of countrys

### ISSUE THREAD

**Issue by tgmorais** [BONSAMURAIS/BONSAI-ontology-RDF-framework#18]
We need a uri for EXIOBASE aggregation of country, as Rest of Europe.

**Comment by tgmorais** [comment]
This was already solved.

**Comment by kuzeko** [comment]
@tmillross  can you add how this was resolved with an example?

**Comment by tmillross** [comment]
@kuzeko added location example to readme

**Comment by kuzeko** [comment]
@tmillross  sorry, autocomplete failure again, I meant to refer to @tgmorais1
