### ISSUE TITLE
Include namespace to specify year

### ISSUE THREAD

**Issue by agneta20** [BONSAMURAIS/BONSAI-ontology-RDF-framework#21]

**Comment by kuzeko** [comment]
Possibly we do

 `http://rdf.bonsai.uno/time/2011` 
and point to sameAs `http://reference.data.gov.uk/doc/year/2011` and same as  `https://www.wikidata.org/wiki/Q1994`

**Comment by agneta20** [comment]
[Namespace created] (https://github.com/BONSAMURAIS/rdf/commit/52f7ff3cd69eb3172f21518746b92a53c28b347f)
