### ISSUE TITLE
The diagram is not up to date with the schema

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/BONSAI-ontology-RDF-framework#23]
In the picture diagram the predicate names between Activity and ActivityType and between Flow and FlowObject are not the correct one.

**Comment by agneta20** [comment]
New schema added in .png and .svg formats.
Two examples added as graphical representation

**Comment by kuzeko** [comment]
i've removed the png.
The svg is just a download of 
http://www.visualdataweb.de/webvowl/#iri=https://ontology.bonsai.uno/core/ontology_v0.1.rdf
