### ISSUE TITLE
Define a BONSAI prefix 

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/BONSAI-ontology-RDF-framework#3]
We need a prefix (namespace) for BONSAI vocabulary.

Probably there should be a prefix for `core` ontology concept so that we can have separate namespaces for other vocabularies.

The prefix could be something like 
`http://bonsai.uno/rdf/ontology/core#`

**Comment by agneta20** [comment]
+1

**Comment by mmr2187** [comment]
+1

what prefix if ever though? I think since this is the baseline, core should be sufficient.

**Comment by massimopizzol** [comment]
+1

**Comment by agneta20** [comment]
Some update- the prefix should have ontology.bonsai.uno

**Comment by agneta20** [comment]
Tomas will upload it the bonsai.uno server

**Comment by kuzeko** [comment]
Ok so the namespace will be 

`http://ontology.bonsai.uno/core#`

So we can have data under

`http://rdf.bonsai.uno/instance#`
or 
`http://data.bonsai.uno/instances#`

etc...

**Comment by kuzeko** [comment]
The group agreed on using the subdomain "ontology.bonsai.uno"
The ttl files will be in `https://github.com/BONSAMURAIS/ontology` and the contents of the repository will be deployed on the server

**Comment by agneta20** [comment]
Finalized on the subdomain namespace. Issue closed.
