### ISSUE TITLE
Produce RDF Schema in  RDF/XML format

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/BONSAI-ontology-RDF-framework#4]
The core  RDF Schema should be formalized in TTL format based on 
the final high level schema. (see:  [Schema proposed by BONSAI_v1.md](https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework/blob/master/Schema%20proposed%20by%20BONSAI_v1.md)   )

This depends on #3

**Comment by kuzeko** [comment]
The output of this should be actually updated in
[ontology_v0.1.rdf](https://github.com/BONSAMURAIS/ontology/blob/master/core/ontology_v0.1.rdf)

**Comment by kuzeko** [comment]
We should validate the ontology with something like:

http://oops.linkeddata.es/

**Comment by ntropy-esa** [comment]
Other validator 
https://www.w3.org/RDF/Validator/

**Comment by kuzeko** [comment]
this is the integration with jena/riot
https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework/commit/76d1a09ce5978753ef38b5e082ce4abe2eca9057

instructions here
https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework/blob/master/HowTo_Converter.md
