### ISSUE TITLE
Missing concept modeling: Property relation

### ISSUE THREAD

**Issue by agneta20** [BONSAMURAIS/BONSAI-ontology-RDF-framework#6]
Property relation refers the quantity of a datapoint should be seen as proportional to. For example, a flow of a specific quantity of 'steel' from an activity - 'steel production' may be related to another flow of this activity (e.g. 5 tons) or to a time period (per year).

We are not sure of existing ontologies that have worked with this concept. The proposal is to develop one specific for bonsai and if existing ontologies are found we can link to it later

**Comment by mmr2187** [comment]
I was thinking it could be a flow-object divided by a flow-object but this might be too simplistic as the scaling might not be correct in the dataset. But perhaps a simple correction via a multiplier would work?

(copied from my email)

**Comment by boweidema** [comment]
General format in everyday language: Flow F is given in proportion to X amount of [Time OR Flow G] of activity A (this last information may be omitted if we require that Flow F and G are always from the same activity, but the more general option is to specify the activity)

Alternative formalisation: Flow A hasPropertyRelation of amount X of [Time OR Flow G] of activity A



Example 1: 614790.55 tonne of Rice output hasPropertyRelation of 1 year of Time of Australian rice production

Example 2: 5.5 tonne of carbon dioxide output hasPropertyRelation of 1000 kg of steel output of Australian steel production

Example 3: 444 tonne of carbon dioxide output hasPropertyRelation of 614790.55 tonne of Rice output of Australian rice production

(numbers in examples are not necessarily reflection any real size of flows)



Possible RDF formalisation of Example 1:

    "measure":{

        "@type":"om:Measure",

        "om:hasNumericalValue":"614790.55",

        "om:hasUnit":"om:tonne",

        "propertyRelation":{

            "activity":"A_PARI",

            "om:hasNumericalValue":"1",

            "om:hasUnit":"om:year"

        }

**Comment by agneta20** [comment]
Hi everyone 
We have added property relation to the ontology . However we use different terminology:
1. we now have a class - "Reference Unit" which has a property- "proportionalTo" Flow and property "referenceFlowObject".
2. Domains for both properties are Flow and Flow object respectively. 
3. For definitions on the new classes and ontologies please refer to [ontology](https://ontology.bonsai.uno/core/)
